"""tables

Revision ID: 796c2e643aee
Revises: edd684b23970
Create Date: 2023-04-05 14:33:14.355885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796c2e643aee'
down_revision = 'edd684b23970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
